{% set name = "paramak" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/paramak-{{ version }}.tar.gz
  sha256: a08b911049c11e4295b744917290028ffd8c423f2ecca98b539c5374ae17df44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=72.1.0
    - setuptools-scm >=8.1.0
    - pip
  run:
    - python >={{ python_min }}
    - cadquery >=2.5.2
    - numpy
    - mpmath
    - sympy
    - scipy

test:
  imports:
    - paramak
  requires:
    - python {{ python_min }}
    - pip
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: https://github.com/fusion-energy/paramak
  summary: Create 3D fusion reactor CAD models based on input parameters
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shimwell
